In [1]:
import pandas as pd
import yfinance as yf 
import os

In [3]:
TICKER = "JNJ"
START_DATE = "2016-01-01"
END_DATE = "2026-01-01"

In [4]:
df = yf.download(TICKER, start=START_DATE, end=END_DATE, auto_adjust=False, progress=False
)

In [5]:
df.head()

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,JNJ,JNJ,JNJ,JNJ,JNJ,JNJ
Date,,,,,,
2016-01-04,76.173637,100.480003,101.809998,99.449997,101.709999,12722800
2016-01-05,76.492050,100.900002,101.440002,100.570000,100.580002,6467200
2016-01-06,76.105408,100.389999,100.970001,99.599998,99.820000,7733800
2016-01-07,75.218430,99.220001,100.089996,98.879997,99.309998,9433100
2016-01-08,74.414856,98.160004,99.940002,97.849998,99.879997,9766700

In [6]:
df.index = pd.to_datetime(df.index)
df = df.sort_index()
df = df.dropna()
df.columns = df.columns.droplevel("Ticker")
df.head()

Price,Adj Close,Close,High,Low,Open,Volume
Date,,,,,,
2016-01-04,76.173637,100.480003,101.809998,99.449997,101.709999,12722800
2016-01-05,76.492050,100.900002,101.440002,100.570000,100.580002,6467200
2016-01-06,76.105408,100.389999,100.970001,99.599998,99.820000,7733800
2016-01-07,75.218430,99.220001,100.089996,98.879997,99.309998,9433100
2016-01-08,74.414856,98.160004,99.940002,97.849998,99.879997,9766700

In [8]:
os.makedirs("../data/raw", exist_ok=True)
df.to_csv("../data/prices_JNJ.csv")